### ------------------Clean Comtrade Data Notebook-----------------------
This notebook cleans the raw UN Comtrade bilateral exports dataset and creates an analytics-ready Comtrade file. Note : This notebook does not modify or delete your raw Comtrade files.

In [1]:
# Import necessary libraries
import os
from datetime import datetime
import numpy as np
import pandas as pd

In [ ]:
# Define file paths for raw and processed data
RAW_COMTRADE_FILE = r"C:\Users\hp\OneDrive\Desktop\global-trade-supply-chain-intelligence\data\raw_data\comtrade_data\world_bilateral_exports_final_total_2015_2024_20260706_031419.csv"
PROCESSED_OUTPUT_DIR = r"C:\Users\hp\OneDrive\Desktop\global-trade-supply-chain-intelligence\data\processed_data"

os.makedirs(PROCESSED_OUTPUT_DIR, exist_ok=True)

print("Raw file path:")
print(RAW_COMTRADE_FILE)
print("Processed output folder:")
print(PROCESSED_OUTPUT_DIR)

Raw file path:
C:\Users\hp\OneDrive\Desktop\global-trade-supply-chain-intelligence\data\raw_data\comtrade_data\world_bilateral_exports_final_total_2015_2024_20260706_031419.csv
Processed output folder:
C:\Users\hp\OneDrive\Desktop\global-trade-supply-chain-intelligence\data\processed_data

In [4]:
# Loading the raw dataset
df_raw = pd.read_csv(RAW_COMTRADE_FILE)

print("Raw dataset loaded successfully.")
print(f"Rows: {df_raw.shape[0]:,}")
print(f"Columns: {df_raw.shape[1]:,}")

Raw dataset loaded successfully.
Rows: 227,574
Columns: 50

In [5]:
df_raw.head()

,typecode,freqcode,refperiodid,refyear,refmonth,period,reportercode,reporteriso,reporterdesc,flowcode,...,isgrosswgtestimated,cifvalue,fobvalue,primaryvalue,legacyestimationflag,isreported,isaggregate,download_year,reporter_batch_number,download_timestamp
0,C,A,20150101,2015,52,2015,4,AFG,Afghanistan,X,...,False,NaN,571404967.0,571404967.0,0,True,False,2015,1,2026-07-06 03:01:42
1,C,A,20150101,2015,52,2015,4,AFG,Afghanistan,X,...,False,NaN,3410.0,3410.0,0,True,False,2015,1,2026-07-06 03:01:42
2,C,A,20150101,2015,52,2015,4,AFG,Afghanistan,X,...,False,NaN,1296260.0,1296260.0,0,True,False,2015,1,2026-07-06 03:01:42
3,C,A,20150101,2015,52,2015,4,AFG,Afghanistan,X,...,False,NaN,51916.0,51916.0,0,True,False,2015,1,2026-07-06 03:01:42
4,C,A,20150101,2015,52,2015,4,AFG,Afghanistan,X,...,False,NaN,618700.0,618700.0,0,True,False,2015,1,2026-07-06 03:01:42

#### Understanding the raw dataset structure

In [ ]:
# Listing all the columns in the raw dataset
df_raw.columns.tolist()

['typecode',
 'freqcode',
 'refperiodid',
 'refyear',
 'refmonth',
 'period',
 'reportercode',
 'reporteriso',
 'reporterdesc',
 'flowcode',
 'flowdesc',
 'partnercode',
 'partneriso',
 'partnerdesc',
 'partner2code',
 'partner2iso',
 'partner2desc',
 'classificationcode',
 'classificationsearchcode',
 'isoriginalclassification',
 'cmdcode',
 'cmddesc',
 'aggrlevel',
 'isleaf',
 'customscode',
 'customsdesc',
 'moscode',
 'motcode',
 'motdesc',
 'qtyunitcode',
 'qtyunitabbr',
 'qty',
 'isqtyestimated',
 'altqtyunitcode',
 'altqtyunitabbr',
 'altqty',
 'isaltqtyestimated',
 'netwgt',
 'isnetwgtestimated',
 'grosswgt',
 'isgrosswgtestimated',
 'cifvalue',
 'fobvalue',
 'primaryvalue',
 'legacyestimationflag',
 'isreported',
 'isaggregate',
 'download_year',
 'reporter_batch_number',
 'download_timestamp']

In [ ]:
# Checking info of the raw dataset
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 227574 entries, 0 to 227573
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   typecode                  227574 non-null  str
 1   freqcode                  227574 non-null  str
 2   refperiodid               227574 non-null  int64
 3   refyear                   227574 non-null  int64
 4   refmonth                  227574 non-null  int64
 5   period                    227574 non-null  int64
 6   reportercode              227574 non-null  int64
 7   reporteriso               227574 non-null  str
 8   reporterdesc              227574 non-null  str
 9   flowcode                  227574 non-null  str
 10  flowdesc                  227574 non-null  str
 11  partnercode               227574 non-null  int64
 12  partneriso                227574 non-null  str
 13  partnerdesc               227574 non-null  str
 14  partner2code              227574 non-null  int64
 15  partner2iso               227574 non-null  str
 16  partner2desc              227574 non-null  str
 17  classificationcode        227574 non-null  str
 18  classificationsearchcode  227574 non-null  str
 19  isoriginalclassification  227574 non-null  bool
 20  cmdcode                   227574 non-null  str
 21  cmddesc                   227574 non-null  str
 22  aggrlevel                 227574 non-null  int64
 23  isleaf                    227574 non-null  bool
 24  customscode               227574 non-null  str
 25  customsdesc               227574 non-null  str
 26  moscode                   227574 non-null  int64
 27  motcode                   227574 non-null  int64
 28  motdesc                   227574 non-null  str
 29  qtyunitcode               227574 non-null  int64
 30  qtyunitabbr               0 non-null       float64
 31  qty                       206237 non-null  float64
 32  isqtyestimated            227574 non-null  bool
 33  altqtyunitcode            227574 non-null  int64
 34  altqtyunitabbr            0 non-null       float64
 35  altqty                    206237 non-null  float64
 36  isaltqtyestimated         227574 non-null  bool
 37  netwgt                    177740 non-null  float64
 38  isnetwgtestimated         227574 non-null  bool
 39  grosswgt                  179676 non-null  float64
 40  isgrosswgtestimated       227574 non-null  bool
 41  cifvalue                  50121 non-null   float64
 42  fobvalue                  227572 non-null  float64
 43  primaryvalue              227574 non-null  float64
 44  legacyestimationflag      227574 non-null  int64
 45  isreported                227574 non-null  bool
 46  isaggregate               227574 non-null  bool
 47  download_year             227574 non-null  int64
 48  reporter_batch_number     227574 non-null  int64
 49  download_timestamp        227574 non-null  str
dtypes: bool(8), float64(9), int64(15), str(18)
memory usage: 74.7 MB

In [ ]:
# Getting summary statistics of the raw dataset
df_raw.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
typecode,227574,1,C,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freqcode,227574,1,A,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
refperiodid,227574.0,NaN,NaN,NaN,20194087.263809,28413.782835,20150101.0,20170101.0,20190101.0,20220101.0,20240101.0
refyear,227574.0,NaN,NaN,NaN,2019.398626,2.841378,2015.0,2017.0,2019.0,2022.0,2024.0
refmonth,227574.0,NaN,NaN,NaN,52.0,0.0,52.0,52.0,52.0,52.0,52.0
period,227574.0,NaN,NaN,NaN,2019.398626,2.841378,2015.0,2017.0,2019.0,2022.0,2024.0
reportercode,227574.0,NaN,NaN,NaN,427.142415,252.192666,4.0,204.0,422.0,643.0,894.0
reporteriso,227574,182,NLD,2360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reporterdesc,227574,182,Netherlands,2360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
flowcode,227574,1,X,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
flowdesc,227574,1,Export,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
partnercode,227574.0,NaN,NaN,NaN,431.723123,254.807241,0.0,208.0,428.0,659.0,899.0
partneriso,227574,245,W00,1629,NaN,NaN,NaN,NaN,NaN,NaN,NaN
partnerdesc,227574,246,World,1629,NaN,NaN,NaN,NaN,NaN,NaN,NaN
partner2code,227574.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
partner2iso,227574,1,W00,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
partner2desc,227574,1,World,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
classificationcode,227574,5,H5,105081,NaN,NaN,NaN,NaN,NaN,NaN,NaN
classificationsearchcode,227574,1,HS,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
isoriginalclassification,227574,1,True,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cmdcode,227574,1,TOTAL,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cmddesc,227574,1,All Commodities,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
aggrlevel,227574.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
isleaf,227574,1,False,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customscode,227574,1,C00,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customsdesc,227574,1,TOTAL CPC,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
moscode,227574.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
motcode,227574.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
motdesc,227574,1,TOTAL MOT,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
qtyunitcode,227574.0,NaN,NaN,NaN,-1.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0
qtyunitabbr,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
qty,206237.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
isqtyestimated,227574,1,False,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
altqtyunitcode,227574.0,NaN,NaN,NaN,-1.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0
altqtyunitabbr,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
altqty,206237.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
isaltqtyestimated,227574,1,False,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
netwgt,177740.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
isnetwgtestimated,227574,2,False,126727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
grosswgt,179676.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
isgrosswgtestimated,227574,1,False,227574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cifvalue,50121.0,NaN,NaN,NaN,9670153.457203,412052218.243313,0.0,0.0,0.0,0.0,41697218636.82
fobvalue,227572.0,NaN,NaN,NaN,1491517876.16958,27443738445.717457,0.005,197300.92975,4042654.4695,68488744.316,3593601435602.0
primaryvalue,227574.0,NaN,NaN,NaN,1491506093.230254,27443618141.288284,0.005,197308.176,4042756.708,68499312.948,3593601435602.0
legacyestimationflag,227574.0,NaN,NaN,NaN,1.548384,1.948348,0.0,0.0,0.0,4.0,4.0
isreported,227574,2,False,206237,NaN,NaN,NaN,NaN,NaN,NaN,NaN
isaggregate,227574,2,True,206237,NaN,NaN,NaN,NaN,NaN,NaN,NaN
download_year,227574.0,NaN,NaN,NaN,2019.398626,2.841378,2015.0,2017.0,2019.0,2022.0,2024.0
reporter_batch_number,227574.0,NaN,NaN,NaN,4.875517,2.603676,1.0,3.0,5.0,7.0,9.0
download_timestamp,227574,90,2026-07-06 03:04:01,3025,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Checking for duplicate rows in the raw dataset
duplicate_rows = df_raw.duplicated().sum()
print(f"No of duplicate rows in raw dataset: {duplicate_rows:,}")

No of duplicate rows in raw dataset: 0

In [ ]:
# Checking for missing values and their percentage in the raw dataset
missing_summary = pd.DataFrame({
    "missing_count": df_raw.isna().sum(),
    "missing_pct": (df_raw.isna().mean() * 100).round(2)
}).sort_values("missing_pct", ascending=False)

missing_summary

                          missing_count  missing_pct
altqtyunitabbr                   227574       100.00
qtyunitabbr                      227574       100.00
cifvalue                         177453        77.98
netwgt                            49834        21.90
grosswgt                          47898        21.05
qty                               21337         9.38
altqty                            21337         9.38
refperiodid                           0         0.00
reporterdesc                          0         0.00
flowcode                              0         0.00
flowdesc                              0         0.00
refyear                               0         0.00
refmonth                              0         0.00
period                                0         0.00
reportercode                          0         0.00
reporteriso                           0         0.00
typecode                              0         0.00
freqcode                              0         0.00
classificationcode                    0         0.00
partner2desc                          0         0.00
partner2iso                           0         0.00
partner2code                          0         0.00
partnerdesc                           0         0.00
partneriso                            0         0.00
partnercode                           0         0.00
classificationsearchcode              0         0.00
customsdesc                           0         0.00
customscode                           0         0.00
moscode                               0         0.00
isoriginalclassification              0         0.00
aggrlevel                             0         0.00
isleaf                                0         0.00
cmdcode                               0         0.00
cmddesc                               0         0.00
altqtyunitcode                        0         0.00
isqtyestimated                        0         0.00
motdesc                               0         0.00
qtyunitcode                           0         0.00
motcode                               0         0.00
isaltqtyestimated                     0         0.00
isnetwgtestimated                     0         0.00
isgrosswgtestimated                   0         0.00
fobvalue                              2         0.00
primaryvalue                          0         0.00
legacyestimationflag                  0         0.00
isreported                            0         0.00
isaggregate                           0         0.00
download_year                         0         0.00
reporter_batch_number                 0         0.00
download_timestamp                    0         0.00

#### Standardize column names

In [12]:
# Standardizing column names for better readability
column_rename_map = {
    "typecode": "type_code",
    "freqcode": "freq_code",
    "refperiodid": "ref_period_id",
    "refyear": "reference_year",
    "refmonth": "reference_month",
    "period": "period",
    "reportercode": "reporter_code",
    "reporteriso": "reporter_iso3",
    "reporterdesc": "reporter_name",
    "flowcode": "flow_code",
    "flowdesc": "flow_name",
    "partnercode": "partner_code",
    "partneriso": "partner_iso3",
    "partnerdesc": "partner_name",
    "partner2code": "partner_2_code",
    "partner2iso": "partner_2_iso3",
    "partner2desc": "partner_2_name",
    "classificationcode": "classification_revision_code",
    "classificationsearchcode": "classification_search_code",
    "isoriginalclassification": "is_original_classification",
    "cmdcode": "commodity_code",
    "cmddesc": "commodity_description",
    "aggrlevel": "aggregation_level",
    "isleaf": "is_leaf",
    "customscode": "customs_code",
    "customsdesc": "customs_description",
    "moscode": "mode_of_supply_code",
    "motcode": "mode_of_transport_code",
    "motdesc": "mode_of_transport_description",
    "qtyunitcode": "quantity_unit_code",
    "qtyunitabbr": "quantity_unit_abbreviation",
    "qty": "quantity",
    "isqtyestimated": "is_quantity_estimated",
    "altqtyunitcode": "alternate_quantity_unit_code",
    "altqtyunitabbr": "alternate_quantity_unit_abbreviation",
    "altqty": "alternate_quantity",
    "isaltqtyestimated": "is_alternate_quantity_estimated",
    "netwgt": "net_weight_kg",
    "isnetwgtestimated": "is_net_weight_estimated",
    "grosswgt": "gross_weight_kg",
    "isgrosswgtestimated": "is_gross_weight_estimated",
    "cifvalue": "cif_value_usd",
    "fobvalue": "fob_value_usd",
    "primaryvalue": "trade_value_usd",
    "legacyestimationflag": "legacy_estimation_flag",
    "isreported": "is_reported",
    "isaggregate": "is_aggregate",
    "download_year": "download_year",
    "reporter_batch_number": "reporter_batch_number",
    "download_timestamp": "download_timestamp"
}

df = df_raw.rename(columns=column_rename_map).copy()

print(f"Total columns after renaming: {len(df.columns)}")

Total columns after renaming: 50

In [ ]:
# Checking the new column names after renaming
df.columns.tolist()

['type_code',
 'freq_code',
 'ref_period_id',
 'reference_year',
 'reference_month',
 'period',
 'reporter_code',
 'reporter_iso3',
 'reporter_name',
 'flow_code',
 'flow_name',
 'partner_code',
 'partner_iso3',
 'partner_name',
 'partner_2_code',
 'partner_2_iso3',
 'partner_2_name',
 'classification_revision_code',
 'classification_search_code',
 'is_original_classification',
 'commodity_code',
 'commodity_description',
 'aggregation_level',
 'is_leaf',
 'customs_code',
 'customs_description',
 'mode_of_supply_code',
 'mode_of_transport_code',
 'mode_of_transport_description',
 'quantity_unit_code',
 'quantity_unit_abbreviation',
 'quantity',
 'is_quantity_estimated',
 'alternate_quantity_unit_code',
 'alternate_quantity_unit_abbreviation',
 'alternate_quantity',
 'is_alternate_quantity_estimated',
 'net_weight_kg',
 'is_net_weight_estimated',
 'gross_weight_kg',
 'is_gross_weight_estimated',
 'cif_value_usd',
 'fob_value_usd',
 'trade_value_usd',
 'legacy_estimation_flag',
 'is_reported',
 'is_aggregate',
 'download_year',
 'reporter_batch_number',
 'download_timestamp']

#### Inspect important business columns

In [14]:
# Displaying value counts for selected columns to understand their distribution
for col in ["type_code", "freq_code", "flow_code", "flow_name", "commodity_code", "commodity_description"]:
    print(f"\nValue counts for {col}:")
    print(df[col].value_counts(dropna=False).head(20))

Value counts for type_code:
type_code
C    227574
Name: count, dtype: int64

Value counts for freq_code:
freq_code
A    227574
Name: count, dtype: int64

Value counts for flow_code:
flow_code
X    227574
Name: count, dtype: int64

Value counts for flow_name:
flow_name
Export    227574
Name: count, dtype: int64

Value counts for commodity_code:
commodity_code
TOTAL    227574
Name: count, dtype: int64

Value counts for commodity_description:
commodity_description
All Commodities    227574
Name: count, dtype: int64

In [15]:
print("Reference years present in dataset:")
print(sorted(df["reference_year"].dropna().unique().tolist()))

Reference years present in dataset:
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

In [16]:
print("Classification revision codes present:")
print(sorted(df["classification_revision_code"].dropna().unique().tolist()))

Classification revision codes present:
['H2', 'H3', 'H4', 'H5', 'H6']

In [ ]:
# Deciding which columns should be kept for the analytics-ready file
columns_to_keep = [
    "reference_year",
    "period",
    "reporter_code",
    "reporter_iso3",
    "reporter_name",
    "partner_code",
    "partner_iso3",
    "partner_name",
    "trade_value_usd",
    "fob_value_usd",
    "flow_code",
    "flow_name",
    "commodity_code",
    "commodity_description",
    "type_code",
    "freq_code",
    "classification_revision_code",
    "is_reported",
    "is_aggregate",
    "download_timestamp"
]

df_clean = df[columns_to_keep].copy()

print(f"Rows: {df_clean.shape[0]:,}")
print(f"Columns kept: {df_clean.shape[1]}")

Rows: 227,574
Columns kept: 20

In [18]:
df_clean.head()

,reference_year,period,reporter_code,reporter_iso3,reporter_name,partner_code,partner_iso3,partner_name,trade_value_usd,fob_value_usd,flow_code,flow_name,commodity_code,commodity_description,type_code,freq_code,classification_revision_code,is_reported,is_aggregate,download_timestamp
0,2015,2015,4,AFG,Afghanistan,0,W00,World,571404967.0,571404967.0,X,Export,TOTAL,All Commodities,C,A,H2,True,False,2026-07-06 03:01:42
1,2015,2015,4,AFG,Afghanistan,31,AZE,Azerbaijan,3410.0,3410.0,X,Export,TOTAL,All Commodities,C,A,H2,True,False,2026-07-06 03:01:42
2,2015,2015,4,AFG,Afghanistan,36,AUS,Australia,1296260.0,1296260.0,X,Export,TOTAL,All Commodities,C,A,H2,True,False,2026-07-06 03:01:42
3,2015,2015,4,AFG,Afghanistan,40,AUT,Austria,51916.0,51916.0,X,Export,TOTAL,All Commodities,C,A,H2,True,False,2026-07-06 03:01:42
4,2015,2015,4,AFG,Afghanistan,50,BGD,Bangladesh,618700.0,618700.0,X,Export,TOTAL,All Commodities,C,A,H2,True,False,2026-07-06 03:01:42

In [ ]:
# Converting data types for better analysis and storage efficiency
numeric_int_cols = [
    "reference_year",
    "period",
    "reporter_code",
    "partner_code"
]

for col in numeric_int_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce").astype("Int64")

numeric_value_cols = [
    "trade_value_usd",
    "fob_value_usd"
]

for col in numeric_value_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

flag_cols = ["is_reported", "is_aggregate"]

for col in flag_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce").astype("Int64")

df_clean["download_timestamp"] = pd.to_datetime(
    df_clean["download_timestamp"],
    errors="coerce",
    dayfirst=True
)

string_cols = [
    "reporter_iso3", "reporter_name",
    "partner_iso3", "partner_name",
    "flow_code", "flow_name",
    "commodity_code", "commodity_description",
    "type_code", "freq_code",
    "classification_revision_code"
]

for col in string_cols:
    df_clean[col] = df_clean[col].astype("string").str.strip()

print("Data type conversion completed.")

Data type conversion completed.

In [20]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 227574 entries, 0 to 227573
Data columns (total 20 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   reference_year                227574 non-null  Int64
 1   period                        227574 non-null  Int64
 2   reporter_code                 227574 non-null  Int64
 3   reporter_iso3                 227574 non-null  string
 4   reporter_name                 227574 non-null  string
 5   partner_code                  227574 non-null  Int64
 6   partner_iso3                  227574 non-null  string
 7   partner_name                  227574 non-null  string
 8   trade_value_usd               227574 non-null  float64
 9   fob_value_usd                 227572 non-null  float64
 10  flow_code                     227574 non-null  string
 11  flow_name                     227574 non-null  string
 12  commodity_code                227574 non-null  string
 13  commodity_description         227574 non-null  string
 14  type_code                     227574 non-null  string
 15  freq_code                     227574 non-null  string
 16  classification_revision_code  227574 non-null  string
 17  is_reported                   227574 non-null  Int64
 18  is_aggregate                  227574 non-null  Int64
 19  download_timestamp            227574 non-null  datetime64[us]
dtypes: Int64(6), datetime64[us](1), float64(2), string(11)
memory usage: 36.0 MB

#### Add a World partner flag
##### Rows where `partner_iso3 = 'W00'` represent reporter-to-world totals rather than bilateral partner rows. This flag makes those rows easier to identify later.

In [22]:
df_clean["is_world_partner"] = pd.Series(
    np.where(df_clean["partner_iso3"] == "W00", 1, 0),
    index=df_clean.index
).astype("Int64")

df_clean["is_world_partner"].value_counts(dropna=False)

is_world_partner
0    225945
1      1629
Name: count, dtype: Int64

In [23]:
# Checking for missing values and their percentage in the cleaned dataset
clean_missing_summary = pd.DataFrame({
    "missing_count": df_clean.isna().sum(),
    "missing_pct": (df_clean.isna().mean() * 100).round(2)
}).sort_values("missing_pct", ascending=False)

clean_missing_summary

                              missing_count  missing_pct
reference_year                            0          0.0
period                                    0          0.0
reporter_code                             0          0.0
reporter_iso3                             0          0.0
reporter_name                             0          0.0
partner_code                              0          0.0
partner_iso3                              0          0.0
partner_name                              0          0.0
trade_value_usd                           0          0.0
fob_value_usd                             2          0.0
flow_code                                 0          0.0
flow_name                                 0          0.0
commodity_code                            0          0.0
commodity_description                     0          0.0
type_code                                 0          0.0
freq_code                                 0          0.0
classification_revision_code              0          0.0
is_reported                               0          0.0
is_aggregate                              0          0.0
download_timestamp                        0          0.0
is_world_partner                          0          0.0

In [24]:
# Checking for duplicate rows based on business key columns
business_key_cols = [
    "reference_year",
    "reporter_code",
    "partner_code",
    "commodity_code",
    "flow_code"
]

duplicate_business_rows = df_clean.duplicated(subset=business_key_cols).sum()

print("Duplicate rows based on business key:")
print(duplicate_business_rows)

Duplicate rows based on business key:
0

#### Basic data quality checks

In [25]:
negative_trade_rows = (df_clean["trade_value_usd"] < 0).sum()
print(f"Rows with negative trade values: {negative_trade_rows:,}")

print("\nReference year min / max:")
print(df_clean["reference_year"].min(), df_clean["reference_year"].max())

print("\nFlow code distribution:")
print(df_clean["flow_code"].value_counts(dropna=False))

print("\nCommodity code distribution:")
print(df_clean["commodity_code"].value_counts(dropna=False))

Rows with negative trade values: 0

Reference year min / max:
2015 2024

Flow code distribution:
flow_code
X    227574
Name: count, dtype: Int64

Commodity code distribution:
commodity_code
TOTAL    227574
Name: count, dtype: Int64

#### Setting final column order for the analytics-ready dataset

In [26]:
final_column_order = [
    "reference_year",
    "period",
    "reporter_code",
    "reporter_iso3",
    "reporter_name",
    "partner_code",
    "partner_iso3",
    "partner_name",
    "is_world_partner",
    "trade_value_usd",
    "fob_value_usd",
    "flow_code",
    "flow_name",
    "commodity_code",
    "commodity_description",
    "type_code",
    "freq_code",
    "classification_revision_code",
    "is_reported",
    "is_aggregate",
    "download_timestamp"
]

df_final = df_clean[final_column_order].copy()
df_final.head()

,reference_year,period,reporter_code,reporter_iso3,reporter_name,partner_code,partner_iso3,partner_name,is_world_partner,trade_value_usd,...,flow_code,flow_name,commodity_code,commodity_description,type_code,freq_code,classification_revision_code,is_reported,is_aggregate,download_timestamp
0,2015,2015,4,AFG,Afghanistan,0,W00,World,1,571404967.0,...,X,Export,TOTAL,All Commodities,C,A,H2,1,0,2026-06-07 03:01:42
1,2015,2015,4,AFG,Afghanistan,31,AZE,Azerbaijan,0,3410.0,...,X,Export,TOTAL,All Commodities,C,A,H2,1,0,2026-06-07 03:01:42
2,2015,2015,4,AFG,Afghanistan,36,AUS,Australia,0,1296260.0,...,X,Export,TOTAL,All Commodities,C,A,H2,1,0,2026-06-07 03:01:42
3,2015,2015,4,AFG,Afghanistan,40,AUT,Austria,0,51916.0,...,X,Export,TOTAL,All Commodities,C,A,H2,1,0,2026-06-07 03:01:42
4,2015,2015,4,AFG,Afghanistan,50,BGD,Bangladesh,0,618700.0,...,X,Export,TOTAL,All Commodities,C,A,H2,1,0,2026-06-07 03:01:42

#### Saving the final cleaned Comtrade dataset

In [27]:
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

output_file_name = f"comtrade_exports_clean_analytics_ready_{timestamp}.csv"
output_file_path = os.path.join(PROCESSED_OUTPUT_DIR, output_file_name)

df_final.to_csv(output_file_path, index=False)

print("Cleaned Comtrade analytics-ready file saved successfully.")
print(output_file_path)

Cleaned Comtrade analytics-ready file saved successfully.
C:\Users\hp\OneDrive\Desktop\global-trade-supply-chain-intelligence\data\processed_data\comtrade_exports_clean_analytics_ready_20260708_020613.csv

#### Final summary of the cleaned output

In [29]:
print("----CLEANED COMTRADE DATA SUMMARY----")
print(f"Rows: {df_final.shape[0]:,}")
print(f"Columns: {df_final.shape[1]:,}")
print(f"Reference year range: {df_final['reference_year'].min()} to {df_final['reference_year'].max()}")
print(f"World-partner rows: {df_final['is_world_partner'].sum():,}")
print(f"Cleaned output file: {output_file_path}")

----CLEANED COMTRADE DATA SUMMARY----
Rows: 227,574
Columns: 21
Reference year range: 2015 to 2024
World-partner rows: 1,629
Cleaned output file: C:\Users\hp\OneDrive\Desktop\global-trade-supply-chain-intelligence\data\processed_data\comtrade_exports_clean_analytics_ready_20260708_020613.csv